Update how to push one github repository files to another github repository

diff --git a/how to push one github repository files to another github repository b/how to push one github repository files to another github repository
--- a/how to push one github repository files to another github repository
+++ b/how to push one github repository files to another github repository
@@ -27,6 +27,7 @@ pipeline {
                         git url: env.SOURCE_REPO, credentialsId: env.GIT_CREDENTIALS_ID_PRIMARY
                     } catch (Exception e) {
                         echo 'Unable to clone source repository'
+                        throw e
                     }
                 }
             }
@@ -34,8 +35,13 @@ pipeline {
         
         stage('Clone Destination Repository') {
             steps {
-                dir('../vara') {
-                    git url: env.DEST_REPO, credentialsId: env.GIT_CREDENTIALS_ID_SECONDARY
+                script {
+                    try {
+                        echo 'Cloning the destination repository'
+                        git url: env.DEST_REPO, credentialsId: env.GIT_CREDENTIALS_ID_SECONDARY
+                    } catch (Exception e){
+                        echo 'Unable to clone destination repository'
+                    }
                 }
             }
         }
@@ -43,19 +49,26 @@ pipeline {
         stage('Copy Files') {
             steps {
                 script {
-                    sh 'cp -r * ../vara'
+                    sh 'rsync -a --exclude=.git ./ destination-repo/'
                 }
             }
         }
 
-        
-
         stage('Push Files to Destination Repo') {
             steps {
-                dir('../vara') {
-                    sh 'git add .'
-                    sh 'git commit -m "vara is added"'
-                    sh 'git push origin var'
+                dir('destination-repo') {
+                    script {
+                        withCredentials([usernamePassword(credentialsId: "${env.GIT_CREDENTIALS_ID_SECONDARY}", usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
+                            sh "git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/ravularajesh3333/vara.git"
+                            sh '''
+                            git fetch origin
+                            git checkout var
+                            '''
+                            sh 'git add .'
+                            sh 'git commit -m "Files copied from source repo" || echo "No changes to commit"'
+                            sh 'git push origin var'
+                        }
+                    }
                 }
             }
         }
